apiVersion: v1
kind: Service
metadata:
  name: train-app-service
  namespace: tim
  annotations:
    prometheus.io/scrape: 'true'    # 这个 annotation 是话给 prometheus听，让 prometheus 去 scape /metrics 里的数据。
spec:
  selector:
    hello: cake
  type: NodePort      # ClusterIP 不能用喔。 说port有问题.
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: train-app
    protocol: TCP
    port: 5000
    targetPort: 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app-deploy
  namespace: tim
  labels:
    app: train-app-metadata
    team: authn
spec:
  selector:
    matchLabels:
      app: train-app-template
      hello: cake
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: train-app-template
        hello: cake
    spec:
      imagePullSecrets:
      - name: regcred   
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: train-schedule
        image: $IMAGE:$BUILD_NUMBER
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          # limits:
          #   cpu: 100m
          #   memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: my.app
        #       key: DB_HOST
        ports:
        - containerPort: 8080
          name: my-app       
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoScaler
metadata:
  name: train-schedule-hpa
  namespace: tim
spec:
  scalTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-app-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resources
      resource:
        name: cpu
        targetAverageUtilization: 50  # average cpu usage 50% across all pods
